# Generated by Django 2.2.5 on 2019-09-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=16, verbose_name='标题')),
                ('note', models.TextField(max_length=150, verbose_name='备注信息')),
                ('image', models.ImageField(upload_to='banner', verbose_name='图片')),
                ('link', models.CharField(max_length=64, verbose_name='链接')),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
                'db_table': 'luffy_banner',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=50, verbose_name='导航名称')),
                ('link', models.CharField(max_length=350, verbose_name='导航地址')),
                ('opt', models.SmallIntegerField(choices=[(0, '顶部导航'), (1, '底部导航')], default=0, verbose_name='位置')),
            ],
            options={
                'verbose_name': '导航条',
                'verbose_name_plural': '导航条',
                'db_table': 'luffy_navigation',
            },
        ),
    ]
